import {
  inherit,
  current,
  transparent,
  black,
  white,
  slate,
  gray,
  zinc,
  neutral,
  stone,
  red,
  orange,
  amber,
  yellow,
  lime,
  green,
  emerald,
  teal,
  cyan,
  sky,
  blue,
  indigo,
  violet,
  purple,
  fuchsia,
  pink,
  rose,
} from "tailwindcss/colors";

export const Colors = {
  ...{
    inherit,
    current,
    transparent,
    black,
    white,
    slate,
    gray,
    zinc,
    neutral,
    stone,
    red,
    orange,
    amber,
    yellow,
    lime,
    green,
    emerald,
    teal,
    cyan,
    sky,
    blue,
    indigo,
    violet,
    purple,
    fuchsia,
    pink,
    rose,
  },
  light: {
    invertText: neutral[50],
    background: neutral[50],
    card: stone[100],
    text: stone[800],
    border: gray[800],
    notification: gray[800],
    active: cyan[600],
    primary: blue[500],
    secondary: gray[400],
    danger: red[400],
    warning: amber[300],
    success: green[500],
    info: teal[600],
  },

  dark: {
    invertText: stone[800],
    background: gray[600],
    card: stone[900],
    text: neutral[50],
    border: neutral[200],
    notification: neutral[100],
    active: cyan[600],
    primary: blue[500],
    secondary: gray[400],
    danger: red[400],
    warning: amber[300],
    success: green[500],
    info: teal[600],
  },
};
